#!/usr/bin/perl
use warnings;
use strict;
use pg_csv_log_parser;
use pg_csv_log_filters;

my @patterns = map { qr/$_/ } qw(connection);

my $about_connections = has_table \@patterns;

iterate collect output, filter $about_connections, input;


