#!/usr/bin/perl
use warnings;
use strict;
use pg_csv_log_parser;
use pg_csv_log_filters;

my @patterns = (qr/create index/i);

my $create_index = has_table \@patterns;

iterate collect output, filter $create_index, input;


