#!/usr/bin/perl
use warnings;
use strict;
use pg_csv_log_parser;
use pg_csv_log_filters;


my $to = field_has LOG_TIME, '\d{4}-\d{2}-\d{2} ' . shift @ARGV;

iterate collect output, stopgag $to, input;

